matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - pip install mkdocs && mkdocs --version
        - pip install mkdocs-material
      script:
        - mkdocs build

    - language: node_js
      node_js:
        - "8.11.2"
      script:
        - npm run test:eslint
        - npm run test:stylelint
        - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: develop