os: linux

language: python

python: 3.6

branches: develop

cache:
  npm: false
  pip: false

install:
  - pip install --upgrade pip --ignore-installed
  - pip install mkdocs --ignore-installed
  - pip install mkdocs-material ----ignore-installed

matrix:
  include:
    - language: node_js
      node_js: "8.11.2"
      stage: "prepare"
      script:
        - npm install

    - language: python
      python: "3.6"
      stage: "build"
      script:
        - mkdocs build

    - language: node_js
      node_js: "8.11.2"
      stage: "build"
      script:
        - npm run build

    - language: node_js
      node_js: "8.11.2"
      stage: "test"
      script:
        - npm run test:eslint && npm run test:stylelint
