os: linux
language: node_js

install:
  - pip install mkdocs
  - pip install mkdocs-material

matrix:
  include:
    - language: node_js
      node_js: "8.11.2"
      stage: "prepare"
      script:
        - npm install

    - language: python
      python: 2.7
      stage: "build"
      script:
        - mkdocs build

    - language: node_js
      node_js: "8.11.2"
      stage: "build"
      script:
        - npm run build

    - language: node_js
      node_js: "8.11.2"
      stage: "test"
      script:
        - npm run test:eslint && npm run test:stylelint
