os: linux

language: node_js

branches: develop

cache:
  npm: false
  pip: false

matrix:
  include:
    - stage: "docs"
      language: python
      python: 3.6
      before_script:
        - pip install mkdocs
        - pip install mkdocs-material
      script:
        - mkdocs build

    - language: node_js
      node_js: "8.11.2"
      stage: "npm"
      before_script:
        - npm install
      script:
        - npm run build
        - npm run test:eslint && npm run test:stylelint
