stages:
  - prepare
  - build
  - test
  - deploy

prepare:npm:
  stage: prepare
  language: node_js
  node_js:
    - "8.11.2"
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

prepare:mkdocs:
  stage: prepare
  language: python
  python: 2.7
  script:
    - pip install mkdocs && mkdocs --version
    - pip install mkdocs-material

build:npm:
  stage: build
  language: node_js
  node_js:
    - "8.11.2"
  dependencies:
    - prepare:npm
  script:
    - npm run build

build:mkdocs:
  stage: build
  language: python
  python: 2.7
  dependencies:
    - prepare:mkdocs
  script:
    - mkdocs build

test:npm:
  stage: test
  language: node_js
  node_js:
    - "8.11.2"
  dependencies:
    - prepare:npm
    - build:npm
  script:
    - npm run test:eslint && npm run test:stylelint

before_deploy:
  - cd site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  edge: true
  on:
    branch: develop
