os: linux

language: node_js

node_js: "8.11.2"

branches: develop

cache:
  npm: true
  pip: true

jobs:
  include:
    - language: python
      python: 3.6
      before_script:
        - pip install mkdocs
        - pip install mkdocs-material
        - npm install
      script:
        - npm run build
        - npm run test:eslint && npm run test:stylelint
        - npm run build:mkdocs && npm run build
        - rm ./site/demo/index.html
        # - cp -r ./docs/demo/ ./site/demo/
        # - cp -r ./build/ ./site/demo/assets/build/
        - cd site
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        edge: true
        commit_message: Deploy Travis CI to %{target_branch} branch
        on:
          branch: develop
