os: linux

language: node_js

branches: develop

cache:
  npm: true
  pip: true

jobs:
  include:
    - language: node_js
      node_js: "8.11.2"
      python: 3.6
      before_script:
        - pip install mkdocs
        - pip install mkdocs-material
        - npm install
      script:
        - npm run build
        - npm run test:eslint && npm run test:stylelint
        - npm run build:mkdocs
        - cd site
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        edge: true
        on:
          branch: develop
