# Project information
site_name: 'vLite.js'
site_description: 'vLite is a fast and lightweight Javascript library to customize and skin native HTML5 video and Youtube video in Javascript native.'
site_author: 'Joris DANIEL aka Yoriiis'
site_url: 'https://vlite.bitbucket.io'

# Pages
pages:
    - Overview: index.md
    - Getting started: getting-started.md
    - How it works: how-it-works.md
    - Available methods: available-methods.md
    - Demo: demo.md
    - Download: download.md
    - Releases notes: releases-notes.md

# Copyright
copyright: 'Copyright &copy; 2019 - Joris DANIEL aka Yoriiis'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'amber'
    accent: 'amber'
  font:
    text: 'Roboto'
    code: 'Ubuntu Mono'
  logo:
    icon: 'map'
  feature:
    tabs: false

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/yoriiis'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jorisdaniel'

# Google Analytics
google_analytics:
  - 'UA-108758282-2'
  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - meta