name: Docs

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    uses: yoriiis/actions/.github/workflows/test-and-build-root-demo.yml@main
    with:
      working-directory-demo: ./docs
